use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn temp_workspace(name: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time")
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("design_cli_cargo_resolution_{name}_{unique}"));
    fs::create_dir_all(dir.join("src")).expect("src");
    dir
}

fn write_workspace(workspace: &Path) {
    fs::write(
        workspace.join("Cargo.toml"),
        "[package]\nname = \"offline_guard\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("cargo");
    fs::write(
        workspace.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"offline_guard\"\nversion = \"0.1.0\"\n",
    )
    .expect("lock");
    fs::create_dir_all(workspace.join(".cargo")).expect(".cargo");
    fs::write(
        workspace.join(".cargo/config.toml"),
        "[build]\ntarget-dir = \"target\"\n",
    )
    .expect("config");
    fs::write(workspace.join("src/main.rs"), "fn main() {}\n").expect("main");
}

fn install_fake_cargo(workspace: &Path) -> (PathBuf, PathBuf) {
    let bin_dir = workspace.join("fake-bin");
    fs::create_dir_all(&bin_dir).expect("bin dir");
    let log_path = workspace.join("fake-cargo.log");
    let script = bin_dir.join("cargo");
    fs::write(
        &script,
        r#"#!/bin/sh
printf '%s|%s|%s|%s\n' "$PWD" "${CARGO_NET_OFFLINE:-}" "${CARGO_TERM_COLOR:-}" "$*" >> "$HOME/fake-cargo.log"
case "$1" in
  check)
    echo "$*" | grep -- '--offline' >/dev/null 2>&1 || { echo "missing --offline" >&2; exit 97; }
    if [ -f "$HOME/expect_locked" ]; then
      echo "$*" | grep -- '--locked' >/dev/null 2>&1 || { echo "missing --locked" >&2; exit 98; }
    fi
    if [ -f "$HOME/dependency_unavailable" ]; then
      echo 'error: failed to get `petgraph` as a dependency of package `offline_guard v0.1.0`' >&2
      echo 'Caused by:' >&2
      echo '  download of config.json failed' >&2
      echo 'Caused by:' >&2
      echo '  could not resolve host: index.crates.io' >&2
      exit 101
    fi
    exit 0
    ;;
  metadata)
    echo "$*" | grep -- '--offline' >/dev/null 2>&1 || { echo "missing metadata --offline" >&2; exit 99; }
    exit 0
    ;;
  *)
    exit 0
    ;;
esac
"#,
    )
    .expect("script");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&script).expect("metadata").permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&script, perms).expect("chmod");
    }
    (bin_dir, log_path)
}

fn write_workspace_with_subcrate(workspace: &Path) {
    // Root workspace manifest (no [package], just [workspace])
    fs::write(
        workspace.join("Cargo.toml"),
        "[workspace]\nmembers = [\"apps/cli\"]\nresolver = \"2\"\n",
    )
    .expect("root cargo.toml");
    fs::write(
        workspace.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"design_cli\"\nversion = \"0.1.0\"\n",
    )
    .expect("lock");
    fs::create_dir_all(workspace.join(".cargo")).expect(".cargo");
    fs::write(
        workspace.join(".cargo/config.toml"),
        "[build]\ntarget-dir = \"target\"\n",
    )
    .expect("config");

    // Sub-crate: apps/cli
    fs::create_dir_all(workspace.join("apps/cli/src/nl")).expect("nl dir");
    fs::write(
        workspace.join("apps/cli/Cargo.toml"),
        "[package]\nname = \"design_cli\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("cli cargo.toml");
    fs::write(workspace.join("apps/cli/src/main.rs"), "fn main() {}\n").expect("main.rs");
    fs::write(
        workspace.join("apps/cli/src/nl/mod.rs"),
        "pub mod planner_v2;\n",
    )
    .expect("nl/mod.rs");
    fs::write(
        workspace.join("apps/cli/src/nl/planner_v2.rs"),
        "pub fn plan() {}\n",
    )
    .expect("planner_v2.rs");
}

fn binary_path() -> &'static str {
    env!("CARGO_BIN_EXE_design_cli")
}

#[test]
fn transactional_apply_resolves_crate_after_sandbox_rebase() {
    // target: apps/cli/src/nl/planner_v2.rs
    // expect package = design_cli (not "unable to determine affected crate")
    let workspace = temp_workspace("sandbox_rebase");
    write_workspace_with_subcrate(&workspace);
    let (bin_dir, _log_path) = install_fake_cargo(&workspace);
    let path = format!(
        "{}:{}",
        bin_dir.display(),
        std::env::var("PATH").unwrap_or_default()
    );

    let output = Command::new(binary_path())
        .args([
            "coding",
            ".",
            "--target",
            "apps/cli/src/nl/planner_v2.rs",
            "--apply",
        ])
        .current_dir(&workspace)
        .env("PATH", path)
        .env("HOME", &workspace)
        .output()
        .expect("run design_cli");

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let combined = format!("{stdout}{stderr}");
    assert!(
        !combined.contains("unable to determine affected crate"),
        "crate resolution failed — sandbox rebase not normalized:\n{combined}"
    );
}

#[test]
fn coding_check_uses_offline_locked_resolution() {
    let workspace = temp_workspace("offline_locked");
    write_workspace(&workspace);
    let (bin_dir, log_path) = install_fake_cargo(&workspace);
    fs::write(workspace.join("expect_locked"), "1\n").expect("expect locked");
    let path = format!(
        "{}:{}",
        bin_dir.display(),
        std::env::var("PATH").unwrap_or_default()
    );

    let output = Command::new(binary_path())
        .args(["coding", ".", "--check"])
        .current_dir(&workspace)
        .env("PATH", path)
        .env("HOME", &workspace)
        .output()
        .expect("run design_cli");

    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Status: checked"), "{stdout}");

    let log = fs::read_to_string(&log_path).expect("cargo log");
    assert!(
        log.contains("|true|never|check --offline --locked"),
        "{log}"
    );

    let telemetry = fs::read_to_string(workspace.join(".dbm/telemetry/cargo_resolution.json"))
        .expect("cargo telemetry");
    assert!(telemetry.contains("\"offline\": true"), "{telemetry}");
    assert!(telemetry.contains("\"lockfile_used\": true"), "{telemetry}");
    assert!(telemetry.contains("\"cache_hit\": true"), "{telemetry}");
}

#[test]
fn coding_check_reports_dependency_unavailable_without_network() {
    let workspace = temp_workspace("dependency_unavailable");
    write_workspace(&workspace);
    let (bin_dir, log_path) = install_fake_cargo(&workspace);
    fs::write(workspace.join("expect_locked"), "1\n").expect("expect locked");
    fs::write(workspace.join("dependency_unavailable"), "1\n").expect("dependency unavailable");
    let path = format!(
        "{}:{}",
        bin_dir.display(),
        std::env::var("PATH").unwrap_or_default()
    );

    let output = Command::new(binary_path())
        .args(["coding", ".", "--check"])
        .current_dir(&workspace)
        .env("PATH", path)
        .env("HOME", &workspace)
        .output()
        .expect("run design_cli");

    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Status: failed"), "{stdout}");
    assert!(
        stdout.contains("Reason: dependency_unavailable (offline cache miss)"),
        "{stdout}"
    );

    let log = fs::read_to_string(&log_path).expect("cargo log");
    assert!(
        log.contains("|true|never|check --offline --locked"),
        "{log}"
    );
    assert!(log.contains("|true|never|metadata --offline"), "{log}");

    let telemetry = fs::read_to_string(workspace.join(".dbm/telemetry/cargo_resolution.json"))
        .expect("cargo telemetry");
    assert!(telemetry.contains("\"cache_hit\": false"), "{telemetry}");
    assert!(
        telemetry.contains("\"graceful_degradation\": true"),
        "{telemetry}"
    );
    assert!(telemetry.contains("petgraph"), "{telemetry}");
}
