
import pytest
from unittest.mock import MagicMock
from design_brain_model.brain_model.phase18 import (
    CodeSkeletonBuilder, StubBuilder, SoundBox, AutoFix, 
    ReconstructionFeedbackGenerator, ExecutionReport
)
from design_brain_model.brain_model.language_engine.domain import LanguageReport

class TestPhase18Workflow:

    @pytest.fixture
    def mock_l2_unit(self):
        return {
            "candidate_id": "L2-Mock-001",
            "content": "src/module_a/feature_x API", # Implies path structure + API keyword
            "kind": "DECISION"
        }

    @pytest.fixture
    def mock_language_report(self):
        return LanguageReport(
            summary="L2 Summary",
            decision_state="OVERRIDDEN_L2",
            l2_description="Desc",
            override_rationale="Reason",
            differences={},
            non_actions=[],
            scope_limits=[]
        )

    def test_phase18_1_skeleton_builder(self, mock_l2_unit, mock_language_report):
        builder = CodeSkeletonBuilder()
        skeleton = builder.build(mock_l2_unit, "snap-1", mock_language_report)
        
        assert skeleton.directory.paths == ["src/module_a/feature_x"]
        assert skeleton.provenance.l2_id == "L2-Mock-001"
        assert skeleton.provenance.snapshot_id == "snap-1"
        # Type check skeleton exists
        assert "L2Entity" in skeleton.types.types

    def test_phase18_2_stub_builder(self, mock_l2_unit, mock_language_report):
        sk_builder = CodeSkeletonBuilder()
        skeleton = sk_builder.build(mock_l2_unit, "snap-1", mock_language_report)
        
        stub_builder = StubBuilder()
        stubs = stub_builder.build_stubs(skeleton)
        
        path = "src/module_a/feature_x"
        assert f"{path}/__init__.py" in stubs
        assert f"{path}/main.py" in stubs
        
        main_content = stubs[f"{path}/main.py"]
        assert "Generated by Phase18-2" in main_content
        assert "NotImplementedError" in main_content
        assert "class L2Entity" in main_content

    def test_phase18_3_soundbox_execution(self):
        soundbox = SoundBox()
        
        # Valid Python Stub
        stubs_valid = {"main.py": "print('Hello')"}
        report_valid = soundbox.execute(stubs_valid)
        assert report_valid.success is True
        assert len(report_valid.errors) == 0
        
        # Invalid Python Stub
        stubs_invalid = {"main.py": "print('Hello'"} # Syntax Error
        report_invalid = soundbox.execute(stubs_invalid)
        assert report_invalid.success is False
        assert len(report_invalid.errors) > 0
        assert "Syntax Error" in report_invalid.errors[0]

    def test_phase18_3a_autofix_logic(self):
        autofix = AutoFix()
        report = ExecutionReport(
            success=False, logs=[], errors=["Syntax Error: ..."], l2_alignment_diff=[]
        )
        
        # Should be fixable (conceptually)
        assert autofix.is_fixable(report) is True
        
        # Logic mismatch is NOT fixable
        report_logic = ExecutionReport(
             success=False, logs=[], errors=["L2 Logic Mismatch"], l2_alignment_diff=[]
        )
        assert autofix.is_fixable(report_logic) is False

    def test_phase18_3b_feedback_strictness(self):
        generator = ReconstructionFeedbackGenerator()
        
        # Valid Feedback
        report = ExecutionReport(
            success=False, logs=["Error: Timeout"], errors=[], l2_alignment_diff=["Structure Mismatch"]
        )
        feedback = generator.generate("L2-1", "snap-1", report)
        assert feedback.reason == "L2_RESTRUCTURE_REQUIRED"
        
        # Prohibited vocabulary check
        report_bad = ExecutionReport(
            success=False, logs=[], errors=[], l2_alignment_diff=["It is likely wrong"]
        )
        with pytest.raises(ValueError):
            generator.generate("L2-1", "snap-1", report_bad)

