
import pytest
from design_brain_model.brain_model.artifact_pipeline import CodeSkeletonBuilder, StubBuilder
from design_brain_model.brain_model.language_engine.domain import LanguageReport

class TestStubBuilder:
    """
    Tests for Phase18-2: StubBuilder.
    Focuses on A-02 (Responsibility Non-Expansion) and generation correctness.
    """

    @pytest.fixture
    def mock_language_report(self):
        return LanguageReport(
            summary="L2 Summary",
            decision_state="OVERRIDDEN_L2",
            l2_description="Desc",
            override_rationale="Reason",
            differences={},
            non_actions=[],
            scope_limits=[]
        )

    def test_A02_stub_responsibility(self, mock_language_report):
        """
        A-02: Verify stubs are templates and do not contain implementation logic.
        """
        l2_unit = {
            "candidate_id": "L2-TEST-STUB",
            "content": "src/stub_test API", 
            "kind": "DECISION"
        }
        
        # 1. Generate Skeleton
        sk_builder = CodeSkeletonBuilder()
        skeleton = sk_builder.build(l2_unit, "snap-stub", mock_language_report)
        
        # 2. Generate Stubs
        stub_builder = StubBuilder()
        stubs = stub_builder.build_stubs(skeleton)
        
        # Verify Files
        main_file = "src/stub_test/main.py"
        assert main_file in stubs
        content = stubs[main_file]
        
        # Verify Header/Provenance
        assert "Generated by ArtifactPipeline-2" in content
        assert "L2 Source: L2-TEST-STUB" in content
        
        # Verify No Logic (NotImplementedError)
        assert "NotImplementedError" in content
        assert "TODO" in content
        
        # Verify Type Definitions
        assert "class L2Entity" in content
        
        # Verify API Stubs (if present in skeleton)
        assert "class Service" in content
        assert "def get_handler(self):" in content # Assumes default GET method
