name: Nightly

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  nightly:
    name: Nightly CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master

      - uses: Swatinem/rust-cache@v2

      - name: ignored tests
        run: cargo test --workspace -- --ignored

      - name: benchmark
        run: cargo bench --workspace

      - name: install cargo-audit
        run: cargo install cargo-audit --locked

      - name: security audit
        run: cargo audit
