name: Nightly

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  nightly:
    name: Nightly CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master

      - uses: Swatinem/rust-cache@v2

      - name: release suite
        run: bash scripts/run_ci_test_suite.sh all --release

      - name: experimental tests
        run: bash scripts/run_ci_test_suite.sh experiments

      - name: install cargo-audit
        run: cargo install cargo-audit --locked

      - name: security audit
        run: cargo audit
